window.appData = {
  config: {
    logo: "https://picsum.photos/200/100",
    logo_b64: "",
    name: "METRO BOGOTA",
    color_titulo: "#ffffff",
    size_titulo: "30px",
    switch_theme: true,
  },
  themes: {
    primary: {
      name: "tema 1",
      primario: "#d32f2f",
      primarioHover: "#b71c1c",
      fondoGlobal: "#f4f6f8",
      fondoPanel: "#ffffff",
      textoPrincipal: "#333333",
      textoSecundario: "#666666",
      bordes: "#e0e0e0",
    },
    secondary: {
      name: "tema 2",
      primario: "#1976d2",
      primarioHover: "#115293",
      fondoGlobal: "#e3f2fd",
      fondoPanel: "#ffffff",
      textoPrincipal: "#0d47a1",
      textoSecundario: "#546e7a",
      bordes: "#bbdefb",
    },
  },
};

window.AuthData = {
  roles: {
    admin: { modeProfile: "manipular", showSchedule: true, showTrends: true },
    operador: {
      modeProfile: "manipular",
      showSchedule: false,
      showTrends: false,
    },
    invitado: { modeProfile: "ver", showSchedule: false, showTrends: false },
  },
  users: {
    admin: "admin",
    pedro_op: "operador",
    visitante1: "invitado",
  },
};

window.appData.levels = [
  {
    id: "piso_1",
    label: "Piso 1 - Áreas Comunes",
    //roles_permission: ["invitado"],
    //denied_users: ["admin"],
    //url_lm: "http://192.168.0.174/scada-vis",
    zones: [
      {
        id: "z_recepcion",
        label: "Recepción y Lobby",
        //roles_permission: ["invitado"],
        //denied_users: ["admin"],
        //url_lm: "http://192.168.0.174/scada-vis",
        systems: [
          {
            id: "sys1",
            category: "sys_ilu",
            label: "Iluminación",
            view_type: "tarjetas_mixtas",
            //roles_permission: ["invitado"],
            //denied_users: ["admin"],
            data: [
              {
                //roles_permission: ["invitado"],
                //denied_users: ["admin"],
                id: "c1",
                circuit: "L12",
                card_type: "app-card-ilu",
                name: "Ducto Edificación 1",
                on_off: "1/1/1",
                rs_on_off: "1/2/1",
                byte: "1/3/1",
                rs_byte: "1/4/1",
                url_schedule: "/scada-vis/schedulers?id=1&nohol",
                url_trend: "/scada-vis/trends?id=1&mode=day",
                sensor: {
                  name: "SP3-12",
                  dg_tiempo: "2/1/1",
                  unidad: "min",
                  limite_maximo: 20,
                  dg_bloqueo: "2/1/4",
                  url_schedule: "/scada-vis/schedulers?id=1&nohol",
                  url_trend: "/scada-vis/trends?id=1&mode=day",
                },
              },
            ],
          },
          {
            id: "sys2",
            category: "sys_clima",
            label: "Climatizacion",
            view_type: "tarjetas_mixtas",
            data: [
              {
                id: "clima1",
                card_type: "app-card-acc",
                name: "Modo Reunión",
                on_off: "4/1/1",
                rs_on_off: "4/1/2",
                url_schedule: "/scada-vis/schedulers?id=1&nohol",
                url_trend: "/scada-vis/trends?id=1&mode=day",
                consigna: {
                  dg_action: "4/1/3",
                  min_limit: 16,
                  max_limit: 30,
                  url_schedule: "/scada-vis/schedulers?id=1&nohol",
                  url_trend: "/scada-vis/trends?id=1&mode=day",
                },
                rs_consigna: "4/1/4",
                mode: {
                  dg_action: "4/1/5",
                  cool: { name: "frio", value: 1 },
                  fan: { name: "ventilador", value: 2 },
                  heat: { name: "calor", value: 3 },
                  humedad: { name: "humedad", value: 4 },
                  auto: { name: "auto", value: 5 },
                  dry: { name: "dry", value: 6 },
                },
                rs_mode: "4/1/6",
                speed: {
                  dg_action: "4/1/7",
                  spped_1: { name: "vel 1", value: 1 },
                  spped_2: { name: "vel 2", value: 2 },
                  spped_3: { name: "vel 3", value: 3 },
                  spped_4: { name: "vel 4", value: 4 },
                },
                rs_speed: "4/1/8",
                swim: "4/1/9",
                rs_swim: "4/1/10",
              },
            ],
          },
          {
            id: "sys3",
            category: "sys_cort",
            label: "Cortinas",
            view_type: "tarjetas_mixtas",
            data: [
              {
                id: "cort1",
                card_type: "app-card-curtain",
                name: "alcoba 1",
                move: {
                  dg_mover: "5/1/1",
                  open: 0,
                  close: 1,
                },
                stop: "5/1/2",
                position: "5/1/3",
                rs_position: "5/1/4",
                url_schedule: "/scada-vis/schedulers?id=1&nohol",
                url_trend: "/scada-vis/trends?id=1&mode=day",
              },
            ],
          },
          {
            id: "sys4",
            label: "Escenas",
            category: "sys_scene",
            view_type: "tarjetas_mixtas",
            data: [
              {
                id: "esc1",
                card_type: "app-card-scene",
                name: "Modo Reunión",
                dg_ejecutar: "2/1/4",
                valor: "23",
              },
            ],
          },
          {
            id: "sys5",
            label: "Crear Escenas",
            category: "sys_g_scene",
            view_type: "generador_escenas",
            data: [],
          },
        ],
      },
      {
        id: "z_cava_p1",
        label: "Cava de Vinos",
        //url_lm: "http://192.168.0.174/scada-vis",
        systems: [
          {
            id: "sys_clima_cava1",
            category: "sys_clima",
            label: "Climatizacion",
            view_type: "tarjetas_mixtas",
            data: [
              {
                id: "ac2",
                card_type: "app-card-acc",
                name: "Refrigeración Cava",
                on_off: "3/1/2",
                rs_on_off: "3/2/2",
                consigna: "3/3/2",
                rs_consigna: "3/4/2",
                temp_actual: "3/5/2",
              },
            ],
          },
          {
            id: "sys_ilu_cava1",
            category: "sys_ilu",
            label: "Iluminación",
            view_type: "tarjetas_mixtas",
            data: [
              {
                id: "c90",
                circuit: "L13",
                card_type: "app-card-ilu",
                name: "Focos Cava",
                on_off: "1/1/3",
                rs_on_off: "1/2/3",
                byte: "1/3/3",
                rs_byte: "1/4/3",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "piso_2",
    label: "Piso 2 - Residencial",
    zones: [
      {
        id: "z_gran_comedor_p2",
        label: "Gran Comedor",
        systems: [
          {
            id: "sys1",
            category: "multi_view",
            label: "multi card",
            view_type: "tarjetas_mixtas",
            data: [
              {
                id: "c12",
                circuit: "L21",
                card_type: "app-card-ilu",
                name: "Ducto Edificación 1",
                on_off: "1/1/1",
                rs_on_off: "1/2/1",
                byte: "1/3/1",
                rs_byte: "1/4/1",
                url_schedule: "/scada-vis/schedulers?id=1&nohol",
                url_trend: "/scada-vis/trends?id=1&mode=day",
                sensor: {
                  name: "SP3-13",
                  dg_tiempo: "2/1/1",
                  unidad: "min",
                  limite_maximo: 20,
                  dg_bloqueo: "2/1/4",
                  url_schedule: "/scada-vis/schedulers?id=1&nohol",
                  url_trend: "/scada-vis/trends?id=1&mode=day",
                },
              },
              {
                id: "esc1",
                card_type: "app-card-scene",
                name: "Modo Reunión",
                dg_ejecutar: "2/1/4",
                valor: "1",
                data_type: "bool",
              },
              {
                id: "clima1",
                card_type: "app-card-acc",
                name: "Modo Reunión",
                on_off: "4/1/1",
                rs_on_off: "4/1/2",
                url_schedule: "/scada-vis/schedulers?id=1&nohol",
                url_trend: "/scada-vis/trends?id=1&mode=day",
                consigna: {
                  dg_action: "4/1/3",
                  min_limit: 16,
                  max_limit: 30,
                  url_schedule: "/scada-vis/schedulers?id=1&nohol",
                  url_trend: "/scada-vis/trends?id=1&mode=day",
                },
                rs_consigna: "4/1/4",
                mode: {
                  dg_action: "4/1/5",
                  cool: { name: "frio", value: 1 },
                  fan: { name: "ventilador", value: 2 },
                  heat: { name: "calor", value: 3 },
                  humedad: { name: "humedad", value: 4 },
                  auto: { name: "auto", value: 5 },
                  dry: { name: "dry", value: 6 },
                },
                rs_mode: "4/1/6",
                speed: {
                  dg_action: "4/1/7",
                  spped_1: { name: "vel 1", value: 1 },
                  spped_2: { name: "vel 2", value: 2 },
                  spped_3: { name: "vel 3", value: 3 },
                  spped_4: { name: "vel 4", value: 4 },
                },
                rs_speed: "4/1/8",
                swim: "4/1/9",
                rs_swim: "4/1/10",
              },
              {
                id: "cort1",
                card_type: "app-card-curtain",
                name: "alcoba 1",
                move: {
                  dg_mover: "5/1/1",
                  open: 0,
                  close: 1,
                },
                stop: "5/1/2",
                position: "5/1/3",
                rs_position: "5/1/4",
                url_schedule: "/scada-vis/schedulers?id=1&nohol",
                url_trend: "/scada-vis/trends?id=1&mode=day",
              },
            ],
          },
          {
            id: "sys2",
            category: "sys_g_scene",
            label: "Crear Escenas",
            view_type: "generador_escenas",
            data: [],
          },
        ],
      },
      {
        id: "z_cava_p2",
        label: "Cava de Vinos",
        systems: [
          {
            id: "sys_clima_cava2",
            category: "sys_clima",
            label: "Control de Humedad y Clima",
            view_type: "tarjetas_mixtas",
            data: [
              {
                id: "ac2",
                card_type: "app-card-acc",
                name: "Refrigeración Cava",
                on_off: "3/1/2",
                rs_on_off: "3/2/2",
                consigna: "3/3/2",
                rs_consigna: "3/4/2",
                temp_actual: "3/5/2",
              },
            ],
          },
          {
            id: "sys_ilu_cava2",
            category: "sys_ilu",
            label: "Iluminación Tenue",
            view_type: "tarjetas_mixtas",
            data: [
              {
                id: "c90",
                circuit: "L14",
                card_type: "app-card-ilu",
                name: "Focos Cava",
                on_off: "1/1/3",
                rs_on_off: "1/2/3",
                byte: "1/3/3",
                rs_byte: "1/4/3",
              },
            ],
          },
        ],
      },
      {
        id: "z_banos_p2",
        label: "Baño Principal",
        systems: [
          {
            id: "sys1",
            label: "Iluminación",
            category: "sys_ilu",
            view_type: "tarjetas_mixtas",
            data: [
              {
                id: "c5",
                circuit: "L15",
                card_type: "app-card-ilu",
                name: "Espejo y Ducha",
                on_off: "1/1/5",
                rs_on_off: "1/2/5",
                sensor: {
                  name: "SP3-14",
                  dg_tiempo: "2/1/1",
                  unidad: "min",
                  limite_maximo: 15,
                  dg_bloqueo: "2/1/4",
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "piso_3",
    label: "Piso 3 - Máquinas",
    url_lm: "http://192.168.0.174/scada-vis/",
  },
];

window.state = {
  themeActive: "primary",
  currentPage: 1,
  itemsByPage: 10,
};
